/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request, 
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	SmPoliciesPost(http.ResponseWriter, *http.Request)
	SmPoliciesSmPolicyIdDeletePost(http.ResponseWriter, *http.Request)
	SmPoliciesSmPolicyIdGet(http.ResponseWriter, *http.Request)
	SmPoliciesSmPolicyIdUpdatePost(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	SmPoliciesPost(SmPolicyContextData) (interface{}, error)
	SmPoliciesSmPolicyIdDeletePost(string, SmPolicyDeleteData) (interface{}, error)
	SmPoliciesSmPolicyIdGet(string) (interface{}, error)
	SmPoliciesSmPolicyIdUpdatePost(string, SmPolicyUpdateContextData) (interface{}, error)
}
