/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// SmPoliciesPost - 
func (s *DefaultApiService) SmPoliciesPost(smPolicyContextData SmPolicyContextData) (interface{}, error) {
	// TODO - update SmPoliciesPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'SmPoliciesPost' not implemented")
}

// SmPoliciesSmPolicyIdDeletePost - 
func (s *DefaultApiService) SmPoliciesSmPolicyIdDeletePost(smPolicyId string, smPolicyDeleteData SmPolicyDeleteData) (interface{}, error) {
	// TODO - update SmPoliciesSmPolicyIdDeletePost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'SmPoliciesSmPolicyIdDeletePost' not implemented")
}

// SmPoliciesSmPolicyIdGet - 
func (s *DefaultApiService) SmPoliciesSmPolicyIdGet(smPolicyId string) (interface{}, error) {
	// TODO - update SmPoliciesSmPolicyIdGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'SmPoliciesSmPolicyIdGet' not implemented")
}

// SmPoliciesSmPolicyIdUpdatePost - 
func (s *DefaultApiService) SmPoliciesSmPolicyIdUpdatePost(smPolicyId string, smPolicyUpdateContextData SmPolicyUpdateContextData) (interface{}, error) {
	// TODO - update SmPoliciesSmPolicyIdUpdatePost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'SmPoliciesSmPolicyIdUpdatePost' not implemented")
}
