/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type SmPolicyContextData struct {

	AccNetChId AccNetChId `json:"accNetChId,omitempty"`

	ChargEntityAddr AccNetChargingAddress `json:"chargEntityAddr,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	Supi string `json:"supi"`

	InterGrpIds []string `json:"interGrpIds,omitempty"`

	PduSessionId int32 `json:"pduSessionId"`

	PduSessionType PduSessionType `json:"pduSessionType"`

	Chargingcharacteristics string `json:"chargingcharacteristics,omitempty"`

	Dnn string `json:"dnn"`

	NotificationUri string `json:"notificationUri"`

	AccessType AccessType `json:"accessType,omitempty"`

	RatType RatType `json:"ratType,omitempty"`

	ServingNetwork NetworkId `json:"servingNetwork,omitempty"`

	UserLocationInfo UserLocation `json:"userLocationInfo,omitempty"`

	UeTimeZone string `json:"ueTimeZone,omitempty"`

	Pei string `json:"pei,omitempty"`

	Ipv4Address string `json:"ipv4Address,omitempty"`

	Ipv6AddressPrefix Ipv6Prefix `json:"ipv6AddressPrefix,omitempty"`

	// Indicates the IPv4 address domain
	IpDomain string `json:"ipDomain,omitempty"`

	SubsSessAmbr Ambr `json:"subsSessAmbr,omitempty"`

	SubsDefQos SubscribedDefaultQos `json:"subsDefQos,omitempty"`

	// Contains the number of supported packet filter for signalled QoS rules.
	NumOfPackFilter int32 `json:"numOfPackFilter,omitempty"`

	// If it is included and set to true, the online charging is applied to the PDU session.
	Online bool `json:"online,omitempty"`

	// If it is included and set to true, the offline charging is applied to the PDU session.
	Offline bool `json:"offline,omitempty"`

	// If it is included and set to true, the 3GPP PS Data Off is activated by the UE.
	Var3gppPsDataOffStatus bool `json:"3gppPsDataOffStatus,omitempty"`

	// If it is included and set to true, the reflective QoS is supported by the UE.
	RefQosIndication bool `json:"refQosIndication,omitempty"`

	TraceReq *TraceData `json:"traceReq,omitempty"`

	SliceInfo Snssai `json:"sliceInfo"`

	QosFlowUsage QosFlowUsage `json:"qosFlowUsage,omitempty"`

	ServNfId ServingNfIdentity `json:"servNfId,omitempty"`

	SuppFeat string `json:"suppFeat,omitempty"`

	SmfId string `json:"smfId,omitempty"`

	RecoveryTime time.Time `json:"recoveryTime,omitempty"`
}
