/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ServingNfIdentity struct {

	ServNfInstId string `json:"servNfInstId,omitempty"`

	Guami Guami `json:"guami,omitempty"`

	AnGwAddr AnGwAddress `json:"anGwAddr,omitempty"`
}
