/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresenceInfo struct {

	PraId string `json:"praId,omitempty"`

	PresenceState PresenceState `json:"presenceState,omitempty"`

	TrackingAreaList []Tai `json:"trackingAreaList,omitempty"`

	EcgiList []Ecgi `json:"ecgiList,omitempty"`

	NcgiList []Ncgi `json:"ncgiList,omitempty"`

	GlobalRanNodeIdList []GlobalRanNodeId `json:"globalRanNodeIdList,omitempty"`
}
