/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SessionRuleReport struct {

	// Contains the identifier of the affected session rule(s).
	RuleIds []string `json:"ruleIds"`

	RuleStatus RuleStatus `json:"ruleStatus"`

	SessRuleFailureCode SessionRuleFailureCode `json:"sessRuleFailureCode,omitempty"`
}
