/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type SmPolicyUpdateContextData struct {

	// The policy control reqeust trigges which are met.
	RepPolicyCtrlReqTriggers []PolicyControlRequestTrigger `json:"repPolicyCtrlReqTriggers,omitempty"`

	// Indicates the access network charging identifier for the PCC rule(s) or whole PDU session.
	AccNetChIds []AccNetChId `json:"accNetChIds,omitempty"`

	AccessType AccessType `json:"accessType,omitempty"`

	RatType RatType `json:"ratType,omitempty"`

	ServingNetwork NetworkId `json:"servingNetwork,omitempty"`

	UserLocationInfo UserLocation `json:"userLocationInfo,omitempty"`

	UeTimeZone string `json:"ueTimeZone,omitempty"`

	RelIpv4Address string `json:"relIpv4Address,omitempty"`

	Ipv4Address string `json:"ipv4Address,omitempty"`

	// Indicates the IPv4 address domain
	IpDomain string `json:"ipDomain,omitempty"`

	Ipv6AddressPrefix Ipv6Prefix `json:"ipv6AddressPrefix,omitempty"`

	RelIpv6AddressPrefix Ipv6Prefix `json:"relIpv6AddressPrefix,omitempty"`

	RelUeMac string `json:"relUeMac,omitempty"`

	UeMac string `json:"ueMac,omitempty"`

	SubsSessAmbr Ambr `json:"subsSessAmbr,omitempty"`

	SubsDefQos SubscribedDefaultQos `json:"subsDefQos,omitempty"`

	// Contains the number of supported packet filter for signalled QoS rules.
	NumOfPackFilter int32 `json:"numOfPackFilter,omitempty"`

	// Contains the usage report
	AccuUsageReports []AccuUsageReport `json:"accuUsageReports,omitempty"`

	// If it is included and set to true, the 3GPP PS Data Off is activated by the UE.
	Var3gppPsDataOffStatus bool `json:"3gppPsDataOffStatus,omitempty"`

	// Report the start/stop of the application traffic and detected SDF descriptions if applicable.
	AppDetectionInfos []AppDetectionInfo `json:"appDetectionInfos,omitempty"`

	// Used to report the PCC rule failure.
	RuleReports []RuleReport `json:"ruleReports,omitempty"`

	// Used to report the session rule failure.
	SessRuleReports []SessionRuleReport `json:"sessRuleReports,omitempty"`

	// QoS Notification Control information.
	QncReports []QosNotificationControlInfo `json:"qncReports,omitempty"`

	UserLocationInfoTime time.Time `json:"userLocationInfoTime,omitempty"`

	// Reports the changes of presence reporting area.
	RepPraInfos map[string]PresenceInfo `json:"repPraInfos,omitempty"`

	UeInitResReq UeInitiatedResourceRequest `json:"ueInitResReq,omitempty"`

	// If it is included and set to true, the reflective QoS is supported by the UE. If it is included and set to false, the reflective QoS is revoked by the UE.
	RefQosIndication bool `json:"refQosIndication,omitempty"`

	QosFlowUsage QosFlowUsage `json:"qosFlowUsage,omitempty"`

	CreditManageStatus CreditManagementStatus `json:"creditManageStatus,omitempty"`

	ServNfId ServingNfIdentity `json:"servNfId,omitempty"`

	TraceReq *TraceData `json:"traceReq,omitempty"`
}
