/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RedirectInformation struct {

	// Indicates the redirect is enable.
	RedirectEnabled bool `json:"redirectEnabled,omitempty"`

	RedirectAddressType RedirectAddressType `json:"redirectAddressType,omitempty"`

	// Indicates the address of the redirect server.
	RedirectServerAddress string `json:"redirectServerAddress,omitempty"`
}
