/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthorizedDefaultQos struct {

	Var5qi int32 `json:"5qi,omitempty"`

	Arp Arp `json:"arp,omitempty"`

	PriorityLevel *int32 `json:"priorityLevel,omitempty"`

	AverWindow *int32 `json:"averWindow,omitempty"`

	MaxDataBurstVol *int32 `json:"maxDataBurstVol,omitempty"`

	MaxbrUl *string `json:"maxbrUl,omitempty"`

	MaxbrDl *string `json:"maxbrDl,omitempty"`

	GbrUl *string `json:"gbrUl,omitempty"`

	GbrDl *string `json:"gbrDl,omitempty"`

	// Indicates whether notifications are requested from 3GPP NG-RAN when the GFBR can no longer (or again) be guaranteed for a QoS Flow during the lifetime of the QoS Flow.
	Qnc bool `json:"qnc,omitempty"`
}
