/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ConditionData struct {

	// Uniquely identifies the condition data within a PDU session.
	CondId string `json:"condId"`

	ActivationTime *time.Time `json:"activationTime,omitempty"`

	DeactivationTime *time.Time `json:"deactivationTime,omitempty"`
}
