/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccNetChargingAddress - Describes the network entity within the access network performing charging
type AccNetChargingAddress struct {

	AnChargIpv4Addr string `json:"anChargIpv4Addr,omitempty"`

	AnChargIpv6Addr Ipv6Addr `json:"anChargIpv6Addr,omitempty"`
}
