/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestedQos struct {

	Var5qi int32 `json:"5qi"`

	GbrUl string `json:"gbrUl,omitempty"`

	GbrDl string `json:"gbrDl,omitempty"`
}
